name: Generate and upload custom image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  release:
    types: published

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate autologin image
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python run_all.py
      - name: Upload hex file
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-os-autologin-img
          path: rpiosimage/*-autologin.img
          if-no-files-found: error

  release-asset:
    name: Upload artifact as GH Release asset
    needs: gen-image
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Download updated OS image zip
        uses: actions/download-artifact@v2
        id: download-zip
        with:
          name: raspberry-pi-os-autologin-img
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip.outputs.download-path}}
          asset_name: raspberry-pi-os-${{ steps.get_version.outputs.VERSION }}-autologin-img.zip
          asset_content_type: application/zip
