name: Generate and upload custom image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  release:
    types: published

jobs:
  gen-image:
    runs-on: ubuntu-latest
    name: Generate custom images
    steps:
      - name: Install qemu-img
        run: sudo apt-get update && sudo apt-get install -y qemu-utils
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Download official image and create custom images
        run: python run_all.py
      - name: Upload Nimbus image
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-os-mu
          path: rpiosimage/*-mu.img
          if-no-files-found: error

  release-asset:
    name: Upload artifact as GH Release asset
    needs: gen-image
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Get the GH Release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Download Nimbus image
        uses: actions/download-artifact@v2
        id: download-zip-nimbus
        with:
          name: raspberry-pi-os-nimbus
          path: nimbus
      - name: Zip image again
        run: |
          cd ${{steps.download-zip-nimbus.outputs.download-path}}
          ls
          zip -r raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-nimbus.zip ./*
      - name: Upload Nimbus image as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-zip-nimbus.outputs.download-path}}/raspberry-pi-os-lite-${{ steps.get_version.outputs.VERSION }}-nimbus.zip
          asset_name: raspberry-pi-os-lite-buster-${{ steps.get_version.outputs.VERSION }}-nimbus.zip
          asset_content_type: application/zip
