name: Generate autologin image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  gen-image:
    strategy:
      matrix:
        os: [ubuntu-16.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build.py ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python add_autologin.py
      - name: Upload hex file
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-os-autologin-img
          path: rpiosimage/*-autologin.img
          if-no-files-found: error
